### ISSUE TITLE
Add "show notes" to videos

### ISSUE THREAD

**Issue by crwhitesides** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-1#2]
It would be useful to be able to access additional information regarding topics, individuals, theory discussed in the lesson. For example, these wold be some of the links included in the "show notes":

- [Wireless of the Future, an interview with Nikola Tesla](https://books.google.com.mx/books?id=nN8DAAAAMBAJ&pg=PA476&lpg=PA476&dq=this+startling+prophecy+is+made+by+Mr.+Nikola+Tesla.+In+speaking+of+the&source=bl&ots=qrfmJsbFoy&sig=XVdA387vNCFI_DQeY6HtPnlip8E&hl=en&sa=X&ved=0ahUKEwiroeTQ7sfSAhUMzGMKHZMsCYIQ6AEIGTAA#v=onepage&q=this%20startling%20prophecy%20is%20made%20by%20Mr.%20Nikola%20Tesla.%20In%20speaking%20of%20the&f=false)
- [Weaving the Web: The Original Design and Ultimate Destiny of the World Wide Web](https://www.amazon.com/Weaving-Web-Original-Ultimate-Destiny/dp/006251587X)
- [Submarine communications cables](https://www.google.com.mx/search?q=submarine+cable&oq=submarine+cab&aqs=chrome.0.0l2j69i57j0l3.5375j0j1&sourceid=chrome&ie=UTF-8)

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion and contribution!
