### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-1#3]
_Suggested Summary_
- In this video, we are introduced to the internet: how it came about, why it is special, what its primary purpose is, the client server model, the conventions that requests / responses abide by, and some of the other tools in place to make it all work.

_Suggested Objectives_
- Explain why technology is really a tool that allows us to communicate and be connected to one another.
- Recall that Tim Berners-Lee invented the World Wide Web and the language it uses to communicate, _HTTP_.
- Understand that the internet and the World Wide Web are different things, the former being invented by Vint Cerf long before Tim Berners-Lee created the latter. 
- Explain how Google revolutionized the search engine (with _PageRank_) by categorizing what websites are about by what other websites say about them.
- Be amazed by the fact that we literally have high capacity optic cables running across the ocean, connecting the world with internet.
- Define _HTTP_ as the language that browsers and servers use to speak to one another through requests and responses.
- Understand that requests and responses are really just long strings, organized by the conventions of HTTP so that browsers and servers can communicate back and forth.
- Use _client server model_ to describe the back and forth process that occurs between clients and servers.
- Utilize the metaphor of an apartment complex to describe the structure of a _URL / URI_ (which contains _protocol_, _domain_, and _resource_ components).
- Describe the various _HTTP verbs_ that define a request and what each of them tell the server about what the client wants to do.
- Describe the various _HTTP response codes_ and what each “level” of response communicates to the client.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
