### ISSUE TITLE
Really cool video

### ISSUE THREAD

**Issue by AdamT213** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-1#4]
In short, I think this video is one of the most amazing and inspirational things that I have seen. So much of what we do and learn in the curriculum is extremely detail-oriented and small scale, so it is nice to be exposed to more big-picture ideas every once in a while. Lectures like this really make me excited about being a programmer. Thanks!

**Comment by curiositypaths** [comment]
Hi there,

We are super happy you enjoyed the video!
