### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by Adjoa** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-1#5]
In this video, Avi takes us through a brief history of the Internet and its underlying ethos. We check out one of its predecessors, and learn about the contributions of several people whose work is the reason we have the Internet and WWW today. Finally, we review how the web works by touching on its major components: client, server, and the protocols and devices that connect them.

* Distinguish between the Internet and the World Wide Web
* Describe what happens when a URL is entered into a browser
* Name some of the major protocols that govern the way the WWW operates
* List the layers of the OSI Model
* Briefly state how data travels via the OSI model
* Define the purpose of HTML
* Define the puspose of HTTP
* Describe what an HTTP request looks like
* List the most popular types of HTTP requests
* Describe the client-server model
* Define client
* Define server
* Explain how client and server work together
* Define URI
* Identify the building blocks of a URI/URL
* Describe how data is transmitted via the TCP/IP protocol
* List the ranges of HTTP status codes and their categories

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
