### ISSUE TITLE
A few comments on the video

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/rack-video-review-how-the-web-works-pt-1#6]
Hi, great video, I learned a lot! I wanted to point out a few inaccuracies that I think would be important to look at revising. Most notably:

1) The confusion between sound waves and electromagnetic waves (or other phenomena)

   a) At 24:10 and 24:40 it is mentioned that wifi signals are acoustic waves. In fact, they are microwaves (ie electromagnetic radiation between the frequencies of 300MHz and 300GHz), specifically at 2.4 GHz and 5GHz for wifi signals. This electromagnetic radiation is converted to electrical currents in the receiver via the use of an antenna. 

  b) At 2:30, it is stated that Tesla believed the world to have an acoustic resonance and he wanted to use this theory to send signals over far distances. In fact, Tesla wanted to harness what he thought was the earth's electrical resonance by using the ground and the sky to complete a circuit. He wanted to generate extremely high voltages at a specific frequency and use the ionosphere as a conductor (via plasma channels) to electrical loads, these loads being anyone who wanted to utilize this energy to power their devices. (Like the article says - he wants to transfer currents not electric waves) Although Tesla believed in a speed-of-light radiation propagation which was longitudinal in nature like sound waves (which does not actually exist as far as we know), I'm not sure if sound waves themselves were ever to be used for information propagation in his system. Also, as the speed of sound is only about 340 m/s, it would take around 3.5 hours for sound waves to travel from NYC to LA. 

2) Sending signals across submarine wires does not take a trivial amount of time

  a) At 34:15, it is stated that it is not a problem to send bytes a million times across the ocean because the speed of light is so fast it would only take microseconds or nanoseconds to complete the trip. 

To demonstrate, we can even look at a single round trip between NYC and the UK. This trip only uses one submarine cable (there are a lot of routes which would be much, much longer, ie from the middle of the US to India), and we can completely disregarded added times to due congestion in switching devices. This short round-trip is about 13,000 km according to one of the cables on the website. The speed of light in a vacuum is 300 million m/s, or 300,000 km/s, but in a cable due to the index of refraction it is more like 200,000 km/s. So, one round-trip in this cable (and this cable only) would take (13,000km) / (200,000 km/s) = 0.065 seconds = 65 ms (milliseconds). This is an order of a thousand times slower than a microsecond and a million times slower than a nanosecond which were the two times stated in the video. If this round trip was taken 1 million times in series, it would take around 18 hours. Also, if you include other delay times ie for actual routing paths (which will be more than just one wire) and switching times, this time increases. A journey from the middle of the US to India could be more like 40,000 km total, which could end up in a single round-trip transit time of hundreds of milliseconds (ie 0.X seconds), which is noticeable to a user. Also, to load a website requires multiple round-trips, not just one, so it can take on the order of multiple seconds. 
 
All this is the reason local caching is used for websites with geographically dispersed customers, because transmitting data these far distances takes an amount of time which is not trivial, but can actually cause users to notice and not want to use that website. 
   
That's all I noticed, I hope it's helpful. Thanks for the video!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#7. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
